linters:
  fast: false
  enable-all: true
  disable:
    # deprecated
    - scopelint
    - golint
    - deadcode
    - exhaustivestruct
    - ifshort
    - structcheck
    - interfacer
    - varcheck
    - nosnakecase
    - maligned
    - execinquery
    - gomnd
    - copyloopvar
    - intrange
    # don't need
    - ireturn
    - depguard
    - dupl

linters-settings:
  paralleltest:
    ignore-missing: true
  testpackage:
    allow-packages:
      - golang
  varnamelen:
    min-name-length: 1
  mnd:
    ignored-numbers:
      - "2"
      - "3"
      - "4"
      - "5"
      - "7"
      - "10"
      - "16"
      - "26"
      - "255"
  cyclop:
    max-complexity: 12
  goconst:
    ignore-strings: 'smoke \d'
  funlen:
    lines: 150
  gosec:
    excludes:
      - G404

run:
  go: "1.21"
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0
