linters:
  fast: false
  enable-all: true
  disable:
    # deprecated: by golangci-lint
    - gomnd
    - execinquery
    - exportloopref
    # useless: we rule dependencies by ourselves
    - depguard

linters-settings:
  testpackage:
    allow-packages:
      - golang
  ireturn:
    allow:
      - error
      - empty
      - generic
  varnamelen:
    ignore-names:
      - i
      - j
      - k
      - m
      - n

run:
  go: "1.22"
  allow-parallel-runners: true
  timeout: 5m

output:
  formats:
    - path: stdout
      format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  show-stats: true
  sort-results: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # simple rules for tests
    - path: _test\.go
      linters:
        - funlen
        - dupl
