version: "2"

linters:
  default: all
  disable:
    # useless: we rule exported by ourselves
    - revive
    # useless: we rule dependencies by ourselves
    - depguard
  settings:
    testpackage:
      allow-packages:
        - golang
    ireturn:
      allow:
        - error
        - empty
        - generic
    varnamelen:
      ignore-names:
        - i
        - j
        - k
        - m
        - n
  exclusions:
    rules:
      # simple rules for tests
      - path: _test\.go
        linters:
          - funlen
          - dupl

formatters:
  enable:
    - gofmt
    - goimports

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

run:
  go: "1.24"
  allow-parallel-runners: true
  timeout: 5m
