linters:
  fast: false
  enable-all: true
  disable:
    # deprecated
    - scopelint
    - golint
    - deadcode
    - exhaustivestruct
    - ifshort
    - structcheck
    - interfacer
    - varcheck
    - nosnakecase
    - maligned
    # don't need
    - ireturn
    - depguard
    - dupl

linters-settings:
  paralleltest:
    ignore-missing: true
  testpackage:
    allow-packages:
      - solutions
  varnamelen:
    min-name-length: 1
  gomnd:
    ignored-numbers:
      - "2"
      - "3"
      - "4"
      - "5"
      - "7"
      - "10"
      - "26"
      - "255"
  funlen:
    lines: 150
  gosec:
    excludes:
      - G404

run:
  go: "1.21"
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0
